/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.security.SecureRandom;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author adel
 */
public class SinglePlayerMap extends javax.swing.JFrame {

    /**
     * Creates new form SpringMap
     */
    public SinglePlayerMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setText("shoot");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton2.setText("mark for defusing");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bullets.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("00:27");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 657));
        jPanel2.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/6.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(330, 180, 50, 130);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/16.png"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(840, 530, 50, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/9.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(160, 340, 50, 130);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/8.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(900, 160, 50, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/7.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(700, 160, 50, 130);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/12.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(850, 330, 50, 140);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/15.png"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(650, 500, 50, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/1.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(120, 20, 50, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/10.png"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(350, 350, 50, 120);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/14.png"))); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(350, 520, 50, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/2.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(390, 0, 50, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/13.png"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 510, 60, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/4.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(810, 10, 50, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/5.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 160, 50, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/11.png"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(660, 360, 50, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/3.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(630, 40, 50, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/springmap.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 660);

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinglePlayerMap().setVisible(true);
            }
        });
    }

    public void addItemC1() {

        choice1.add("1");
        choice1.add("2");

        choice1.add("3");

        choice1.add("4");

        choice1.add("5");

        choice1.add("6");

        choice1.add("7");

        choice1.add("8");

        choice1.add("9");

        choice1.add("10");

        choice1.add("11");

        choice1.add("12");

        choice1.add("13");

        choice1.add("14");

        choice1.add("15");

        choice1.add("16");

    }

    public void showpanel() {
        setResizable(false);
        setVisible(true);
        ImageIcon[] maps={
                new javax.swing.ImageIcon(getClass().getResource("/springmap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/summermap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/fallmap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/wintermap.jpg"))
        };
       if (Settings.getTheme().equals("spring")) {
           jPanel1.setBackground(new java.awt.Color(255, 204, 204));
            jLabel2.setIcon(maps[0]);
        } else if (Settings.getTheme().equals("summer")) {
           jPanel1.setBackground(new java.awt.Color(255, 255, 153));
            jLabel2.setIcon(maps[1]);
        } else if (Settings.getTheme().equals("fall")) {
           jPanel1.setBackground(new java.awt.Color(255, 153, 0));
            jLabel2.setIcon(maps[2]);
        } else if (Settings.getTheme().equals("winter")) {
           jPanel1.setBackground(new java.awt.Color(0, 153, 153));
            jLabel2.setIcon(maps[3]);

        }
        addItemC1();

        swap();

    }
    static int[] uniqueNumberGenerator (int n){
        int [] a=new int[n];
        for (int i=0;i<n;i++){
            a[i]=i;
        }
        int result[]=new int[n];
        int x=n;
        SecureRandom rd=new SecureRandom();
        for (int i = 0;i<n;i++){
            int num=rd.nextInt(x);
            result[i]=a[num];
            a[num]=a[x-1];
            x--;
        }
        return result;




    }
    public void swap(){
        ImageIcon[] chars={
                new javax.swing.ImageIcon(getClass().getResource("/characters/1.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/2.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/3.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/4.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/5.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/6.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/7.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/8.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/9.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/10.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/11.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/12.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/13.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/14.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/15.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/16.png"))
        };


        JLabel labels[]={
                jLabel4,jLabel5,jLabel7,jLabel8,
                jLabel9,jLabel10,jLabel11,jLabel12,
                jLabel13,jLabel14,jLabel15,jLabel16,
                jLabel17,jLabel18,jLabel19,jLabel20
        };


                SecureRandom rd=new SecureRandom();
                int[] random=uniqueNumberGenerator(16);
                int[] swapingChars=new int[16];
                for(int i=0 ; i<16 ;i++){
                    swapingChars[i]=random[i];

                }
        int bomber=swapingChars[15];
        int a=swapingChars[0];
        int b=swapingChars[1];
        int c=swapingChars[2];
        int d=swapingChars[3];
        int e=swapingChars[4];
        int f=swapingChars[5];
        int g=swapingChars[6];
        int h=swapingChars[7];
        int i=swapingChars[8];
        int j=swapingChars[9];
        int k=swapingChars[10];
        int l=swapingChars[11];
        int m=swapingChars[12];
        int n=swapingChars[13];
        int o=swapingChars[14];

        Timer timer = new Timer();
        TimerTask phase1=new TimerTask() {
            @Override
            public void run() {
                labels[a].setIcon(chars[b]);
                labels[b].setIcon(chars[a]);
                labels[c].setIcon(chars[d]);
                labels[d].setIcon(chars[c]);
                labels[bomber].setIcon(chars[m]);
                labels[m].setIcon(chars[bomber]);
            }
        };
        TimerTask phase2=new TimerTask() {
            @Override
            public void run() {
                labels[e].setIcon(chars[f]);
                labels[f].setIcon(chars[e]);
                labels[g].setIcon(chars[h]);
                labels[h].setIcon(chars[g]);
                labels[m].setIcon(chars[n]);
                labels[n].setIcon(chars[bomber]);
            }
        };
        TimerTask phase3=new TimerTask() {
            @Override
            public void run() {
                labels[i].setIcon(chars[j]);
                labels[j].setIcon(chars[i]);
                labels[k].setIcon(chars[l]);
                labels[l].setIcon(chars[k]);
                labels[n].setIcon(chars[o]);
                labels[o].setIcon(chars[bomber]);
            }
        };
        timer.schedule(phase1,30000);
        timer.schedule(phase2,60000);
        timer.schedule(phase3,90000);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
