/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.*;
import java.security.SecureRandom;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author adel
 */
public class SinglePlayerMap extends javax.swing.JFrame {

    /**
     * Creates new form SpringMap
     */
    public SinglePlayerMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setText("shoot");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bullets.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("00:27");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 657));
        jPanel2.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/6.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(330, 180, 50, 130);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/16.png"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(840, 530, 50, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/9.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(160, 340, 50, 130);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/8.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(900, 160, 50, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/7.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(700, 170, 50, 130);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/12.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(850, 330, 50, 140);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/15.png"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(650, 500, 50, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/1.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(120, 20, 50, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/10.png"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(350, 350, 50, 120);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/14.png"))); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(350, 520, 50, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/2.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(390, 0, 50, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/13.png"))); // NOI18N
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 510, 60, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/4.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(810, 10, 50, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/5.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 160, 50, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/11.png"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(660, 360, 50, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/characters/3.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(630, 40, 50, 120);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton18.setEnabled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);
        jButton18.setBounds(130, 510, 30, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton17.setEnabled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);
        jButton17.setBounds(290, 500, 30, 20);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton16.setEnabled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);
        jButton16.setBounds(710, 550, 30, 20);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(800, 590, 30, 20);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton14.setEnabled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);
        jButton14.setBounds(940, 450, 30, 20);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);
        jButton13.setBounds(700, 370, 30, 20);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(440, 390, 30, 20);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(20, 440, 30, 20);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(970, 240, 30, 20);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(710, 170, 30, 20);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(380, 180, 30, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(20, 160, 30, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(760, 60, 30, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(510, 10, 30, 20);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(330, 50, 30, 20);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomb.jpg"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(80, 10, 30, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/springmap.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -10, 1000, 670);

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 440, 260);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vScope.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(240, 310, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hScope.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 160, 40, 30);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hScope.png"))); // NOI18N
        jLabel22.setText("jLabel6");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(490, 160, 40, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vScope.png"))); // NOI18N
        jLabel23.setText("jLabel21");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(240, 10, 40, 40);
        jPanel3.add(jLabel26);
        jLabel26.setBounds(490, 340, 0, 0);

        jButton2.setText("quit");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel24.setText("exploded bombs:");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel25.setText("defused bombs:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel25)))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Dashboard d = new Dashboard();
        d.showpanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinglePlayerMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinglePlayerMap().setVisible(true);
            }
        });
    }

    public void addItemC1() {

        choice1.add("1");
        choice1.add("2");

        choice1.add("3");

        choice1.add("4");

        choice1.add("5");

        choice1.add("6");

        choice1.add("7");

        choice1.add("8");

        choice1.add("9");

        choice1.add("10");

        choice1.add("11");

        choice1.add("12");

        choice1.add("13");

        choice1.add("14");

        choice1.add("15");

        choice1.add("16");

    }

    public void showpanel() {
        setResizable(false);
        setVisible(true);
        JButton[] bombs={jButton3,jButton4,jButton5,jButton6,
                jButton7,jButton8,jButton9,jButton10,
                jButton11,jButton12,jButton13,jButton14,
                jButton15,jButton16,jButton17,jButton18

        };

        ImageIcon[] maps={
                new javax.swing.ImageIcon(getClass().getResource("/springmap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/summermap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/fallmap.jpg")),
                new javax.swing.ImageIcon(getClass().getResource("/wintermap.jpg"))
        };
       if (Settings.getTheme().equals("spring")) {
           jPanel1.setBackground(new java.awt.Color(255, 204, 204));
            jLabel2.setIcon(maps[0]);
            for(int j = 0;j<=15;j++){
                bombs[j].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sdBomb.jpg")));
           }

        } else if (Settings.getTheme().equals("summer")) {
           jPanel1.setBackground(new java.awt.Color(255, 255, 153));
            jLabel2.setIcon(maps[1]);
           for(int j = 0;j<=15;j++) {
               bombs[j].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/sudBomb.jpg")));
           }
           bombs[3].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/su4.jpg")));
           bombs[7].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/su8.jpg")));
        } else if (Settings.getTheme().equals("fall")) {
           jPanel1.setBackground(new java.awt.Color(255, 153, 0));
            jLabel2.setIcon(maps[2]);
           for(int j = 0;j<=15;j++) {
               bombs[j].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/fdBomb.jpg")));
           }
        } else if (Settings.getTheme().equals("winter")) {
           jPanel1.setBackground(new java.awt.Color(0, 153, 153));
            jLabel2.setIcon(maps[3]);
           for(int j = 0;j<=15;j++) {
               bombs[j].setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/wdBomb.jpg")));
           }
        }
        addItemC1();

        swap();
        
    }
    static int[] uniqueNumberGenerator (int n){
        int [] a=new int[n];
        for (int i=0;i<n;i++){
            a[i]=i;
        }
        int result[]=new int[n];
        int x=n;
        SecureRandom rd=new SecureRandom();
        for (int i = 0;i<n;i++){
            int num=rd.nextInt(x);
            result[i]=a[num];
            a[num]=a[x-1];
            x--;
        }
        return result;




    }

    public void swap(){
        JLabel labels[]={
                jLabel4,jLabel5,jLabel7,jLabel8,
                jLabel9,jLabel10,jLabel11,jLabel12,
                jLabel13,jLabel14,jLabel15,jLabel16,
                jLabel17,jLabel18,jLabel19,jLabel20
        };
        ImageIcon[] chars={
                new javax.swing.ImageIcon(getClass().getResource("/characters/1.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/2.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/3.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/4.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/5.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/6.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/7.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/8.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/9.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/10.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/11.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/12.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/13.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/14.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/15.png")),
                new javax.swing.ImageIcon(getClass().getResource("/characters/16.png"))
        };
                SecureRandom rd=new SecureRandom();
                int[] random=uniqueNumberGenerator(16);
                int[] swapingChars=new int[16];
                for(int i=0 ; i<16 ;i++){
                    swapingChars[i]=random[i];

                }
        int bomber=swapingChars[15];
        int a=swapingChars[0];
        int b=swapingChars[1];
        int c=swapingChars[2];
        int d=swapingChars[3];
        int e=swapingChars[4];
        int f=swapingChars[5];
        int g=swapingChars[6];
        int h=swapingChars[7];
        int i=swapingChars[8];
        int j=swapingChars[9];
        int k=swapingChars[10];
        int l=swapingChars[11];
        int m=swapingChars[12];
        int n=swapingChars[13];
        int o=swapingChars[14];

Integer y =new Integer(bomber+1);
jLabel26.setText(y.toString());


        Timer timer = new Timer();
        TimerTask phase1=new TimerTask() {
            @Override
            public void run() {
                labels[a].setIcon(chars[b]);
                labels[b].setIcon(chars[a]);
                labels[c].setIcon(chars[d]);
                labels[d].setIcon(chars[c]);
                labels[bomber].setIcon(chars[m]);
                labels[m].setIcon(chars[bomber]);

            }
        };
        TimerTask phase2=new TimerTask() {
            @Override
            public void run() {
                labels[e].setIcon(chars[f]);
                labels[f].setIcon(chars[e]);
                labels[g].setIcon(chars[h]);
                labels[h].setIcon(chars[g]);
                labels[m].setIcon(chars[n]);
                labels[n].setIcon(chars[bomber]);
            }
        };
        TimerTask phase3=new TimerTask() {
            @Override
            public void run() {
                labels[i].setIcon(chars[j]);
                labels[j].setIcon(chars[i]);
                labels[k].setIcon(chars[l]);
                labels[l].setIcon(chars[k]);
                labels[n].setIcon(chars[o]);
                labels[o].setIcon(chars[bomber]);
            }
        };
        timer.schedule(phase1,10000);
        timer.schedule(phase2,20000);
        timer.schedule(phase3,30000);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private static javax.swing.JLabel jLabel11;
    private static javax.swing.JLabel jLabel12;
    private static javax.swing.JLabel jLabel13;
    private static javax.swing.JLabel jLabel14;
    private static javax.swing.JLabel jLabel15;
    private static javax.swing.JLabel jLabel16;
    private static javax.swing.JLabel jLabel17;
    private static javax.swing.JLabel jLabel18;
    private static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
